features: ['mz', 'drift_time', 'retention_time']

accession: {'drift_time': 'MS:1002476',
            'retention_time': 'MS:1000016'}

peakpick:
  res: [0.002445220947265625, 0.12024688720703125, 0.03858184814453125]
  sigma: [0.004, 0.2, 0.11]
  truncate: 4
  threshold: 0

partition:
  split_on: mz
  size: 500
  overlap: 0.05
  processes: 4

alignment:
  reference: refid
  align: retention_time
  tol: [20.E-6, 0.4, 5]
  threshold: 300
  lowess:
    fraction: 0.15
    iterations: 10
    smoothing: 2
