{% set data = load_setup_py_data(setup_file='../setup.py',
                                 from_recipe_dir=True) %}

package:
  name: deimos
  version: {{ data.get('version') }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - deimos = deimos.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - dask
    - h5py
    - matplotlib
    - numpy
    - pandas
    - pymzml
    - pytables
    - python >=3.7
    - ripser
    - scikit-learn
    - scipy
    - snakemake
    - statsmodels

test:
  imports:
    - deimos
  commands:
    - deimos -h
