dims: ['mz', 'drift_time', 'retention_time']

accession: {'drift_time': 'MS:1002476',
            'retention_time': 'MS:1000016'}

threshold: 20

radius:
  smooth: [2, 2, 1]
  weighted_mean: [2, 8, 0]
